name: CI
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

jobs:
  tox:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.5, 3.6, 3.7, pypy3, 3.8]
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml', 'setup.py', 'setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: install openssl for windows
        if: startsWith(runner.os, 'Windows') && startsWith(matrix.python-version, 'pypy')
        run: |
          choco install openssl -confirm
          echo "::set-env name=LIB::C:\Program Files\OpenSSL-Win64\lib;%LIB%"
          echo "::set-env name=INCLUDE::C:\Program Files\OpenSSL-Win64\include;%INCLUDE%"

      - name: Install
        run: |
          pip install tox

      - name: tox
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tox -e py-test-twlatest,py-test-twtrunk,py-linters,publishcov,release
